[package]
name = "voter-stake-registry"
version = "0.2.4"
description = "a voter weight plugin for spl-governance"
license = "GPL-3.0-or-later"
homepage = "https://github.com/blockworks-foundation/voter-stake-registry"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "voter_stake_registry"
doctest = false

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
localnet = []
test-sbf = []

[dependencies]
# a) for deployment use these
anchor-lang = { version = "0.26.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.26.0" }
# b) while testing, use below dependencies for debugging instead of above ones
# anchor-lang = { git = "https://github.com/microwavedcola1/anchor.git", branch = "master-debug" }
# anchor-spl = { git = "https://github.com/microwavedcola1/anchor.git", branch = "master-debug", features = ["governance"]}

# The rev used for spl-governance must match what the fixture binary
# programs/voter-stake-registry/tests/fixtures/spl_governance.so is built from.

bytemuck = "1.9.1"

# WARNING: Be careful about upgrading the spl-governance dependency!
#          Recently the discriminator for new VoterWeightRecord accounts has changed, and upgrading
#          this dependency here without also upgrading the spl-governance program instance beforehand
#          would lead to VWR accounts that are unusable until the spl-governance program is upgraded.
spl-governance = { version = "=3.1.0", features = ["no-entrypoint"] }
spl-governance-addin-api = "=0.1.3"

solana-program = "1.14.10"
static_assertions = "1.1"

[dev-dependencies]
solana-sdk = "1.14.10"
solana-program-test = "1.14.10"
solana-logger = "1.14.10"
spl-token = { version = "^3.0.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^1.0.3", features = ["no-entrypoint"] }
bytemuck = "^1.7.2"
serde = "^1.0"
bincode = "^1.3.1"
log = "0.4.14"
env_logger = "0.9.0"
base64 = "0.13.0"
